// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/JeongWoo-Seo/eth-mon-svr/internal/gasanalyzer (interfaces: PendingPool)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_pending_pool.go -package=mocks . PendingPool
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	mempool "github.com/JeongWoo-Seo/eth-mon-svr/internal/mempool"
	gomock "go.uber.org/mock/gomock"
)

// MockPendingPool is a mock of PendingPool interface.
type MockPendingPool struct {
	ctrl     *gomock.Controller
	recorder *MockPendingPoolMockRecorder
	isgomock struct{}
}

// MockPendingPoolMockRecorder is the mock recorder for MockPendingPool.
type MockPendingPoolMockRecorder struct {
	mock *MockPendingPool
}

// NewMockPendingPool creates a new mock instance.
func NewMockPendingPool(ctrl *gomock.Controller) *MockPendingPool {
	mock := &MockPendingPool{ctrl: ctrl}
	mock.recorder = &MockPendingPoolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPendingPool) EXPECT() *MockPendingPoolMockRecorder {
	return m.recorder
}

// Snapshot mocks base method.
func (m *MockPendingPool) Snapshot() []mempool.PendingTx {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Snapshot")
	ret0, _ := ret[0].([]mempool.PendingTx)
	return ret0
}

// Snapshot indicates an expected call of Snapshot.
func (mr *MockPendingPoolMockRecorder) Snapshot() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Snapshot", reflect.TypeOf((*MockPendingPool)(nil).Snapshot))
}
