// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/JeongWoo-Seo/eth-mon-svr/internal/processor (interfaces: GasAnalyzer)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_gas_analyzer.go -package=mocks . GasAnalyzer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	big "math/big"
	reflect "reflect"

	gasanalyzer "github.com/JeongWoo-Seo/eth-mon-svr/internal/gasanalyzer"
	types "github.com/ethereum/go-ethereum/core/types"
	gomock "go.uber.org/mock/gomock"
)

// MockGasAnalyzer is a mock of GasAnalyzer interface.
type MockGasAnalyzer struct {
	ctrl     *gomock.Controller
	recorder *MockGasAnalyzerMockRecorder
	isgomock struct{}
}

// MockGasAnalyzerMockRecorder is the mock recorder for MockGasAnalyzer.
type MockGasAnalyzerMockRecorder struct {
	mock *MockGasAnalyzer
}

// NewMockGasAnalyzer creates a new mock instance.
func NewMockGasAnalyzer(ctrl *gomock.Controller) *MockGasAnalyzer {
	mock := &MockGasAnalyzer{ctrl: ctrl}
	mock.recorder = &MockGasAnalyzerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGasAnalyzer) EXPECT() *MockGasAnalyzerMockRecorder {
	return m.recorder
}

// BlockPercentiles mocks base method.
func (m *MockGasAnalyzer) BlockPercentiles(poolData []gasanalyzer.WeightedTip) (map[string]uint64, uint64) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlockPercentiles", poolData)
	ret0, _ := ret[0].(map[string]uint64)
	ret1, _ := ret[1].(uint64)
	return ret0, ret1
}

// BlockPercentiles indicates an expected call of BlockPercentiles.
func (mr *MockGasAnalyzerMockRecorder) BlockPercentiles(poolData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlockPercentiles", reflect.TypeOf((*MockGasAnalyzer)(nil).BlockPercentiles), poolData)
}

// CalculateNextBaseFee mocks base method.
func (m *MockGasAnalyzer) CalculateNextBaseFee(baseFee *big.Int, gasUsed, gasLimit uint64) *big.Int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateNextBaseFee", baseFee, gasUsed, gasLimit)
	ret0, _ := ret[0].(*big.Int)
	return ret0
}

// CalculateNextBaseFee indicates an expected call of CalculateNextBaseFee.
func (mr *MockGasAnalyzerMockRecorder) CalculateNextBaseFee(baseFee, gasUsed, gasLimit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateNextBaseFee", reflect.TypeOf((*MockGasAnalyzer)(nil).CalculateNextBaseFee), baseFee, gasUsed, gasLimit)
}

// CalculateWeightForGasUsed mocks base method.
func (m *MockGasAnalyzer) CalculateWeightForGasUsed(gasUsed, gasLimit uint64) float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateWeightForGasUsed", gasUsed, gasLimit)
	ret0, _ := ret[0].(float64)
	return ret0
}

// CalculateWeightForGasUsed indicates an expected call of CalculateWeightForGasUsed.
func (mr *MockGasAnalyzerMockRecorder) CalculateWeightForGasUsed(gasUsed, gasLimit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateWeightForGasUsed", reflect.TypeOf((*MockGasAnalyzer)(nil).CalculateWeightForGasUsed), gasUsed, gasLimit)
}

// DecayValues mocks base method.
func (m *MockGasAnalyzer) DecayValues() []float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecayValues")
	ret0, _ := ret[0].([]float64)
	return ret0
}

// DecayValues indicates an expected call of DecayValues.
func (mr *MockGasAnalyzerMockRecorder) DecayValues() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecayValues", reflect.TypeOf((*MockGasAnalyzer)(nil).DecayValues))
}

// EffectiveTipFromReceipt mocks base method.
func (m *MockGasAnalyzer) EffectiveTipFromReceipt(effectiveGasPrice, baseFee *big.Int) (uint64, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EffectiveTipFromReceipt", effectiveGasPrice, baseFee)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// EffectiveTipFromReceipt indicates an expected call of EffectiveTipFromReceipt.
func (mr *MockGasAnalyzerMockRecorder) EffectiveTipFromReceipt(effectiveGasPrice, baseFee any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EffectiveTipFromReceipt", reflect.TypeOf((*MockGasAnalyzer)(nil).EffectiveTipFromReceipt), effectiveGasPrice, baseFee)
}

// GetCurrentBlockNumAndTime mocks base method.
func (m *MockGasAnalyzer) GetCurrentBlockNumAndTime() (uint64, uint64) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentBlockNumAndTime")
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(uint64)
	return ret0, ret1
}

// GetCurrentBlockNumAndTime indicates an expected call of GetCurrentBlockNumAndTime.
func (mr *MockGasAnalyzerMockRecorder) GetCurrentBlockNumAndTime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentBlockNumAndTime", reflect.TypeOf((*MockGasAnalyzer)(nil).GetCurrentBlockNumAndTime))
}

// GetPrediction mocks base method.
func (m *MockGasAnalyzer) GetPrediction() gasanalyzer.GasPrediction {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrediction")
	ret0, _ := ret[0].(gasanalyzer.GasPrediction)
	return ret0
}

// GetPrediction indicates an expected call of GetPrediction.
func (mr *MockGasAnalyzerMockRecorder) GetPrediction() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrediction", reflect.TypeOf((*MockGasAnalyzer)(nil).GetPrediction))
}

// Reset mocks base method.
func (m *MockGasAnalyzer) Reset() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Reset")
}

// Reset indicates an expected call of Reset.
func (mr *MockGasAnalyzerMockRecorder) Reset() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reset", reflect.TypeOf((*MockGasAnalyzer)(nil).Reset))
}

// SetReady mocks base method.
func (m *MockGasAnalyzer) SetReady() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetReady")
}

// SetReady indicates an expected call of SetReady.
func (mr *MockGasAnalyzerMockRecorder) SetReady() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetReady", reflect.TypeOf((*MockGasAnalyzer)(nil).SetReady))
}

// UpdateAnalBlockTxPredictionGasResult mocks base method.
func (m *MockGasAnalyzer) UpdateAnalBlockTxPredictionGasResult(result map[string]uint64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateAnalBlockTxPredictionGasResult", result)
}

// UpdateAnalBlockTxPredictionGasResult indicates an expected call of UpdateAnalBlockTxPredictionGasResult.
func (mr *MockGasAnalyzerMockRecorder) UpdateAnalBlockTxPredictionGasResult(result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAnalBlockTxPredictionGasResult", reflect.TypeOf((*MockGasAnalyzer)(nil).UpdateAnalBlockTxPredictionGasResult), result)
}

// UpdateLatestBlockData mocks base method.
func (m *MockGasAnalyzer) UpdateLatestBlockData(header *types.Header, nextBaseFee, cutoff uint64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateLatestBlockData", header, nextBaseFee, cutoff)
}

// UpdateLatestBlockData indicates an expected call of UpdateLatestBlockData.
func (mr *MockGasAnalyzerMockRecorder) UpdateLatestBlockData(header, nextBaseFee, cutoff any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLatestBlockData", reflect.TypeOf((*MockGasAnalyzer)(nil).UpdateLatestBlockData), header, nextBaseFee, cutoff)
}
