// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/JeongWoo-Seo/eth-mon-svr/internal/processor (interfaces: RPCManager)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_rpc_manager.go -package=mocks . RPCManager
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	rpcmanager "github.com/JeongWoo-Seo/eth-mon-svr/internal/network/rpcManager"
	ethclient "github.com/ethereum/go-ethereum/ethclient"
	rpc "github.com/ethereum/go-ethereum/rpc"
	gomock "go.uber.org/mock/gomock"
)

// MockRPCManager is a mock of RPCManager interface.
type MockRPCManager struct {
	ctrl     *gomock.Controller
	recorder *MockRPCManagerMockRecorder
	isgomock struct{}
}

// MockRPCManagerMockRecorder is the mock recorder for MockRPCManager.
type MockRPCManagerMockRecorder struct {
	mock *MockRPCManager
}

// NewMockRPCManager creates a new mock instance.
func NewMockRPCManager(ctrl *gomock.Controller) *MockRPCManager {
	mock := &MockRPCManager{ctrl: ctrl}
	mock.recorder = &MockRPCManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRPCManager) EXPECT() *MockRPCManagerMockRecorder {
	return m.recorder
}

// EthClientFunc mocks base method.
func (m *MockRPCManager) EthClientFunc(ctx context.Context, cost rpcmanager.RPCCost, fn func(*ethclient.Client) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EthClientFunc", ctx, cost, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// EthClientFunc indicates an expected call of EthClientFunc.
func (mr *MockRPCManagerMockRecorder) EthClientFunc(ctx, cost, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EthClientFunc", reflect.TypeOf((*MockRPCManager)(nil).EthClientFunc), ctx, cost, fn)
}

// FetchBatch mocks base method.
func (m *MockRPCManager) FetchBatch(ctx context.Context, cost rpcmanager.RPCCost, elems []rpc.BatchElem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchBatch", ctx, cost, elems)
	ret0, _ := ret[0].(error)
	return ret0
}

// FetchBatch indicates an expected call of FetchBatch.
func (mr *MockRPCManagerMockRecorder) FetchBatch(ctx, cost, elems any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchBatch", reflect.TypeOf((*MockRPCManager)(nil).FetchBatch), ctx, cost, elems)
}
