// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/JeongWoo-Seo/eth-mon-svr/internal/processor (interfaces: PendingPool)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_pending_pool.go -package=mocks . PendingPool
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	blockstore "github.com/JeongWoo-Seo/eth-mon-svr/internal/blockstore"
	types "github.com/ethereum/go-ethereum/core/types"
	gomock "go.uber.org/mock/gomock"
)

// MockPendingPool is a mock of PendingPool interface.
type MockPendingPool struct {
	ctrl     *gomock.Controller
	recorder *MockPendingPoolMockRecorder
	isgomock struct{}
}

// MockPendingPoolMockRecorder is the mock recorder for MockPendingPool.
type MockPendingPoolMockRecorder struct {
	mock *MockPendingPool
}

// NewMockPendingPool creates a new mock instance.
func NewMockPendingPool(ctrl *gomock.Controller) *MockPendingPool {
	mock := &MockPendingPool{ctrl: ctrl}
	mock.recorder = &MockPendingPoolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPendingPool) EXPECT() *MockPendingPoolMockRecorder {
	return m.recorder
}

// Clear mocks base method.
func (m *MockPendingPool) Clear() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Clear")
}

// Clear indicates an expected call of Clear.
func (mr *MockPendingPoolMockRecorder) Clear() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clear", reflect.TypeOf((*MockPendingPool)(nil).Clear))
}

// PushBatch mocks base method.
func (m *MockPendingPool) PushBatch(txs []*types.Transaction, currentBlockNum, curBlockTime uint64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PushBatch", txs, currentBlockNum, curBlockTime)
}

// PushBatch indicates an expected call of PushBatch.
func (mr *MockPendingPoolMockRecorder) PushBatch(txs, currentBlockNum, curBlockTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PushBatch", reflect.TypeOf((*MockPendingPool)(nil).PushBatch), txs, currentBlockNum, curBlockTime)
}

// RemoveByReceipts mocks base method.
func (m *MockPendingPool) RemoveByReceipts(header *types.Header, receipts []*types.Receipt) ([]blockstore.FeeBucketStat, int) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveByReceipts", header, receipts)
	ret0, _ := ret[0].([]blockstore.FeeBucketStat)
	ret1, _ := ret[1].(int)
	return ret0, ret1
}

// RemoveByReceipts indicates an expected call of RemoveByReceipts.
func (mr *MockPendingPoolMockRecorder) RemoveByReceipts(header, receipts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveByReceipts", reflect.TypeOf((*MockPendingPool)(nil).RemoveByReceipts), header, receipts)
}

// RemoveExpired mocks base method.
func (m *MockPendingPool) RemoveExpired(curBlock uint64) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveExpired", curBlock)
	ret0, _ := ret[0].(int)
	return ret0
}

// RemoveExpired indicates an expected call of RemoveExpired.
func (mr *MockPendingPoolMockRecorder) RemoveExpired(curBlock any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveExpired", reflect.TypeOf((*MockPendingPool)(nil).RemoveExpired), curBlock)
}
