// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: fee_bucket.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FeeBucket struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Bucket         uint32                 `protobuf:"varint,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	MinPriority    float64                `protobuf:"fixed64,2,opt,name=min_priority,json=minPriority,proto3" json:"min_priority,omitempty"`
	MaxPriority    float64                `protobuf:"fixed64,3,opt,name=max_priority,json=maxPriority,proto3" json:"max_priority,omitempty"`
	TotalTxCount   uint32                 `protobuf:"varint,4,opt,name=total_tx_count,json=totalTxCount,proto3" json:"total_tx_count,omitempty"`
	AvrWaitBlocks  float64                `protobuf:"fixed64,5,opt,name=avr_wait_blocks,json=avrWaitBlocks,proto3" json:"avr_wait_blocks,omitempty"`
	AvrWaitSeconds float64                `protobuf:"fixed64,6,opt,name=avr_wait_seconds,json=avrWaitSeconds,proto3" json:"avr_wait_seconds,omitempty"`
	WaitBlockCount []*WaitBlockCount      `protobuf:"bytes,7,rep,name=wait_block_count,json=waitBlockCount,proto3" json:"wait_block_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FeeBucket) Reset() {
	*x = FeeBucket{}
	mi := &file_fee_bucket_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeeBucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeeBucket) ProtoMessage() {}

func (x *FeeBucket) ProtoReflect() protoreflect.Message {
	mi := &file_fee_bucket_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeeBucket.ProtoReflect.Descriptor instead.
func (*FeeBucket) Descriptor() ([]byte, []int) {
	return file_fee_bucket_proto_rawDescGZIP(), []int{0}
}

func (x *FeeBucket) GetBucket() uint32 {
	if x != nil {
		return x.Bucket
	}
	return 0
}

func (x *FeeBucket) GetMinPriority() float64 {
	if x != nil {
		return x.MinPriority
	}
	return 0
}

func (x *FeeBucket) GetMaxPriority() float64 {
	if x != nil {
		return x.MaxPriority
	}
	return 0
}

func (x *FeeBucket) GetTotalTxCount() uint32 {
	if x != nil {
		return x.TotalTxCount
	}
	return 0
}

func (x *FeeBucket) GetAvrWaitBlocks() float64 {
	if x != nil {
		return x.AvrWaitBlocks
	}
	return 0
}

func (x *FeeBucket) GetAvrWaitSeconds() float64 {
	if x != nil {
		return x.AvrWaitSeconds
	}
	return 0
}

func (x *FeeBucket) GetWaitBlockCount() []*WaitBlockCount {
	if x != nil {
		return x.WaitBlockCount
	}
	return nil
}

type WaitBlockCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WaitBlock     uint32                 `protobuf:"varint,1,opt,name=wait_block,json=waitBlock,proto3" json:"wait_block,omitempty"`
	TxCount       uint32                 `protobuf:"varint,2,opt,name=tx_count,json=txCount,proto3" json:"tx_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitBlockCount) Reset() {
	*x = WaitBlockCount{}
	mi := &file_fee_bucket_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitBlockCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitBlockCount) ProtoMessage() {}

func (x *WaitBlockCount) ProtoReflect() protoreflect.Message {
	mi := &file_fee_bucket_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitBlockCount.ProtoReflect.Descriptor instead.
func (*WaitBlockCount) Descriptor() ([]byte, []int) {
	return file_fee_bucket_proto_rawDescGZIP(), []int{1}
}

func (x *WaitBlockCount) GetWaitBlock() uint32 {
	if x != nil {
		return x.WaitBlock
	}
	return 0
}

func (x *WaitBlockCount) GetTxCount() uint32 {
	if x != nil {
		return x.TxCount
	}
	return 0
}

type FeeStatisticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Buckets       []*FeeBucket           `protobuf:"bytes,2,rep,name=buckets,proto3" json:"buckets,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeeStatisticsRequest) Reset() {
	*x = FeeStatisticsRequest{}
	mi := &file_fee_bucket_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeeStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeeStatisticsRequest) ProtoMessage() {}

func (x *FeeStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fee_bucket_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeeStatisticsRequest.ProtoReflect.Descriptor instead.
func (*FeeStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_fee_bucket_proto_rawDescGZIP(), []int{2}
}

func (x *FeeStatisticsRequest) GetBuckets() []*FeeBucket {
	if x != nil {
		return x.Buckets
	}
	return nil
}

func (x *FeeStatisticsRequest) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_fee_bucket_proto protoreflect.FileDescriptor

const file_fee_bucket_proto_rawDesc = "" +
	"\n" +
	"\x10fee_bucket.proto\x12\x0egas_monitoring\x1a\x1fgoogle/protobuf/timestamp.proto\"\xab\x02\n" +
	"\tFeeBucket\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\rR\x06bucket\x12!\n" +
	"\fmin_priority\x18\x02 \x01(\x01R\vminPriority\x12!\n" +
	"\fmax_priority\x18\x03 \x01(\x01R\vmaxPriority\x12$\n" +
	"\x0etotal_tx_count\x18\x04 \x01(\rR\ftotalTxCount\x12&\n" +
	"\x0favr_wait_blocks\x18\x05 \x01(\x01R\ravrWaitBlocks\x12(\n" +
	"\x10avr_wait_seconds\x18\x06 \x01(\x01R\x0eavrWaitSeconds\x12H\n" +
	"\x10wait_block_count\x18\a \x03(\v2\x1e.gas_monitoring.WaitBlockCountR\x0ewaitBlockCount\"J\n" +
	"\x0eWaitBlockCount\x12\x1d\n" +
	"\n" +
	"wait_block\x18\x01 \x01(\rR\twaitBlock\x12\x19\n" +
	"\btx_count\x18\x02 \x01(\rR\atxCount\"\x86\x01\n" +
	"\x14FeeStatisticsRequest\x123\n" +
	"\abuckets\x18\x02 \x03(\v2\x19.gas_monitoring.FeeBucketR\abuckets\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB1Z/github.com/JeongWoo-Seo/eth-mon-svr/internal/pbb\x06proto3"

var (
	file_fee_bucket_proto_rawDescOnce sync.Once
	file_fee_bucket_proto_rawDescData []byte
)

func file_fee_bucket_proto_rawDescGZIP() []byte {
	file_fee_bucket_proto_rawDescOnce.Do(func() {
		file_fee_bucket_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fee_bucket_proto_rawDesc), len(file_fee_bucket_proto_rawDesc)))
	})
	return file_fee_bucket_proto_rawDescData
}

var file_fee_bucket_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_fee_bucket_proto_goTypes = []any{
	(*FeeBucket)(nil),             // 0: gas_monitoring.FeeBucket
	(*WaitBlockCount)(nil),        // 1: gas_monitoring.WaitBlockCount
	(*FeeStatisticsRequest)(nil),  // 2: gas_monitoring.FeeStatisticsRequest
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_fee_bucket_proto_depIdxs = []int32{
	1, // 0: gas_monitoring.FeeBucket.wait_block_count:type_name -> gas_monitoring.WaitBlockCount
	0, // 1: gas_monitoring.FeeStatisticsRequest.buckets:type_name -> gas_monitoring.FeeBucket
	3, // 2: gas_monitoring.FeeStatisticsRequest.updated_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_fee_bucket_proto_init() }
func file_fee_bucket_proto_init() {
	if File_fee_bucket_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fee_bucket_proto_rawDesc), len(file_fee_bucket_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fee_bucket_proto_goTypes,
		DependencyIndexes: file_fee_bucket_proto_depIdxs,
		MessageInfos:      file_fee_bucket_proto_msgTypes,
	}.Build()
	File_fee_bucket_proto = out.File
	file_fee_bucket_proto_goTypes = nil
	file_fee_bucket_proto_depIdxs = nil
}
