syntax = "proto3";

package gas_monitoring;

option go_package  = "github.com/JeongWoo-Seo/eth-mon-svr/internal/pb";

import "gas_prediction.proto";
import "fee_bucket.proto";

service GasPredictionService {
    rpc UploadGasPredictions(stream GasPredictionStream) returns (stream GasPredictionResponse);

    rpc UploadFeeBuckets(FeeStatisticsRequest) returns (CommonResponse);
}

message CommonResponse {
    bool success = 1;
    string message = 2;
    ResponseCode code = 3;
}

enum ResponseCode {
    RESPONSE_CODE_UNSPECIFIED = 0;

    SUCCESS = 1;

    INVALID_REQUEST = 2;
    INVALID_DATA = 3;

    INTERNAL_ERROR = 4;
    SERVICE_UNAVAILABLE = 5;
}