// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/JeongWoo-Seo/eth-mon-svr/internal/coordinator (interfaces: PendingProcessor)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_pending_processor.go -package=mocks . PendingProcessor
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	common "github.com/ethereum/go-ethereum/common"
	gomock "go.uber.org/mock/gomock"
)

// MockPendingProcessor is a mock of PendingProcessor interface.
type MockPendingProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockPendingProcessorMockRecorder
	isgomock struct{}
}

// MockPendingProcessorMockRecorder is the mock recorder for MockPendingProcessor.
type MockPendingProcessorMockRecorder struct {
	mock *MockPendingProcessor
}

// NewMockPendingProcessor creates a new mock instance.
func NewMockPendingProcessor(ctrl *gomock.Controller) *MockPendingProcessor {
	mock := &MockPendingProcessor{ctrl: ctrl}
	mock.recorder = &MockPendingProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPendingProcessor) EXPECT() *MockPendingProcessorMockRecorder {
	return m.recorder
}

// GetTxInfo mocks base method.
func (m *MockPendingProcessor) GetTxInfo(ctx context.Context, hashes []common.Hash) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetTxInfo", ctx, hashes)
}

// GetTxInfo indicates an expected call of GetTxInfo.
func (mr *MockPendingProcessorMockRecorder) GetTxInfo(ctx, hashes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTxInfo", reflect.TypeOf((*MockPendingProcessor)(nil).GetTxInfo), ctx, hashes)
}
