// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/JeongWoo-Seo/eth-mon-svr/internal/coordinator (interfaces: BlockProcessor)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_block_processor.go -package=mocks . BlockProcessor
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	types "github.com/ethereum/go-ethereum/core/types"
	gomock "go.uber.org/mock/gomock"
)

// MockBlockProcessor is a mock of BlockProcessor interface.
type MockBlockProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockBlockProcessorMockRecorder
	isgomock struct{}
}

// MockBlockProcessorMockRecorder is the mock recorder for MockBlockProcessor.
type MockBlockProcessorMockRecorder struct {
	mock *MockBlockProcessor
}

// NewMockBlockProcessor creates a new mock instance.
func NewMockBlockProcessor(ctrl *gomock.Controller) *MockBlockProcessor {
	mock := &MockBlockProcessor{ctrl: ctrl}
	mock.recorder = &MockBlockProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlockProcessor) EXPECT() *MockBlockProcessorMockRecorder {
	return m.recorder
}

// CleanupFailedBlock mocks base method.
func (m *MockBlockProcessor) CleanupFailedBlock(ctx context.Context, header *types.Header) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupFailedBlock", ctx, header)
	ret0, _ := ret[0].(error)
	return ret0
}

// CleanupFailedBlock indicates an expected call of CleanupFailedBlock.
func (mr *MockBlockProcessorMockRecorder) CleanupFailedBlock(ctx, header any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupFailedBlock", reflect.TypeOf((*MockBlockProcessor)(nil).CleanupFailedBlock), ctx, header)
}

// CompareFeeHistory mocks base method.
func (m *MockBlockProcessor) CompareFeeHistory(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CompareFeeHistory", ctx)
}

// CompareFeeHistory indicates an expected call of CompareFeeHistory.
func (mr *MockBlockProcessorMockRecorder) CompareFeeHistory(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompareFeeHistory", reflect.TypeOf((*MockBlockProcessor)(nil).CompareFeeHistory), ctx)
}

// HeaderByNumber mocks base method.
func (m *MockBlockProcessor) HeaderByNumber(ctx context.Context, number uint64) (*types.Header, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HeaderByNumber", ctx, number)
	ret0, _ := ret[0].(*types.Header)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HeaderByNumber indicates an expected call of HeaderByNumber.
func (mr *MockBlockProcessorMockRecorder) HeaderByNumber(ctx, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HeaderByNumber", reflect.TypeOf((*MockBlockProcessor)(nil).HeaderByNumber), ctx, number)
}

// Initialize mocks base method.
func (m *MockBlockProcessor) Initialize(ctx context.Context) (*types.Header, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Initialize", ctx)
	ret0, _ := ret[0].(*types.Header)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Initialize indicates an expected call of Initialize.
func (mr *MockBlockProcessorMockRecorder) Initialize(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Initialize", reflect.TypeOf((*MockBlockProcessor)(nil).Initialize), ctx)
}

// ProcessBlock mocks base method.
func (m *MockBlockProcessor) ProcessBlock(ctx context.Context, header *types.Header) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessBlock", ctx, header)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessBlock indicates an expected call of ProcessBlock.
func (mr *MockBlockProcessorMockRecorder) ProcessBlock(ctx, header any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessBlock", reflect.TypeOf((*MockBlockProcessor)(nil).ProcessBlock), ctx, header)
}

// Resync mocks base method.
func (m *MockBlockProcessor) Resync(ctx context.Context) (*types.Header, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resync", ctx)
	ret0, _ := ret[0].(*types.Header)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resync indicates an expected call of Resync.
func (mr *MockBlockProcessorMockRecorder) Resync(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resync", reflect.TypeOf((*MockBlockProcessor)(nil).Resync), ctx)
}
